import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { signIn, signOut, useSession } from 'next-auth/react'
import { useDispatch, useSelector } from 'react-redux'
import { show_snackbar } from '@/redux_stores/snackbar_state'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const dispatch = useDispatch()
  const {is_snackbar_visible, snackbar_content} = useSelector((state:any) => state.snackbar_state)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>              
        <button onClick={()=>dispatch(show_snackbar("content1"))}>CHANGE SNACKBAR STATE</button>
        <button onClick={()=>console.log('Snackbar content', snackbar_content)}>SNACKBAR STATE</button>                        
    </>
  )
}
